version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mobile-app-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mobile-app-api
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - mobile-app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/mobile-app-api --quiet
      interval: 30s
      timeout: 10s
      retries: 3

  # Main API Application
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mobile-app-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://api_user:api_password@mongodb:27017/mobile-app-apinew
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    networks:
      - mobile-app-network
    healthcheck:
      test: ["CMD", "node", "-e", "const http=require('http');http.get('http://localhost:3000/health',(r)=>{process.exit(r.statusCode===200?0:1)}).on('error',()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: mobile-app-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/api.aime.pics-0002/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/api.aime.pics-0002/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      api:
        condition: service_healthy
    networks:
      - mobile-app-network

volumes:
  mongodb_data:
    driver: local

networks:
  mobile-app-network:
    driver: bridge
